# Generated by Django 4.2.6 on 2023-12-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('question', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
