# Generated by Django 4.2.6 on 2023-12-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
