# Generated by Django 4.2.6 on 2023-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlCompressorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listshorturls',
            name='compressed_url',
            field=models.CharField(max_length=200),
        ),
    ]
