# Generated by Django 4.2.6 on 2023-12-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlCompressorApp', '0002_alter_listshorturls_compressed_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListShortUrls',
        ),
    ]
