# Generated by Django 4.2.6 on 2023-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UrlCompressorApp', '0003_delete_listshorturls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAvaliableUniqueKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_avaliable_unique_key', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserved_pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.IntegerField()),
                ('upper_limit', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['lower_limit'], name='UrlCompress_lower_l_5cdfd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListShortUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('unique_key', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['unique_key'], name='UrlCompress_unique__a8b1bc_idx')],
            },
        ),
    ]
