# Generated by Django 4.2.6 on 2023-12-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_email'),
        ('UrlCompressorApp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentavaliableuniquekey',
            name='current_avaliable_unique_key',
        ),
        migrations.AddField(
            model_name='currentavaliableuniquekey',
            name='unique_key',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listshorturls',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
        migrations.AddIndex(
            model_name='listshorturls',
            index=models.Index(fields=['profile'], name='UrlCompress_profile_570e9d_idx'),
        ),
    ]
