# Generated by Django 4.2.6 on 2023-12-17 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UrlCompressorApp', '0005_remove_currentavaliableuniquekey_current_avaliable_unique_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listshorturls',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
