# Generated by Django 4.2.6 on 2023-12-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlCompressorApp', '0006_listshorturls_created_on'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listshorturls',
            name='UrlCompress_profile_570e9d_idx',
        ),
        migrations.RemoveField(
            model_name='listshorturls',
            name='profile',
        ),
    ]
