# Generated by Django 4.2.6 on 2023-12-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UrlCompressorApp', '0007_remove_listshorturls_urlcompress_profile_570e9d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listshorturls',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listshorturls',
            index=models.Index(fields=['user'], name='UrlCompress_user_id_972fa0_idx'),
        ),
    ]
