# Generated by Django 4.2.6 on 2023-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlCompressorApp', '0009_alter_listshorturls_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listshorturls',
            name='short_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
