# Generated by Django 4.2.5 on 2023-09-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlcompressor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urlcompressor',
            new_name='shorturl',
        ),
    ]
